version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: ticketflow_app_dev
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
      - data_volume:/app/data
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - DATABASE_URL=sqlite:////app/railway.db
      - SECRET_KEY=development_secret_key
      - RATE_LIMIT_STORAGE_URI=memory://
    command: python run.py
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/v1/tickets/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - ticketflow_network

  redis:
    image: redis:7-alpine
    container_name: ticketflow_redis_dev
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3
    networks:
      - ticketflow_network

networks:
  ticketflow_network:
    driver: bridge

volumes:
  data_volume:
